name: golangci-lint
on:
  push:
  pull_request:
  schedule:
    - cron: '9 4 20 * *'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo GO_VERSION=skip ./preinstall.sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          